# Generated by Django 4.0.5 on 2022-06-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accfifa',
            name='status',
        ),
        migrations.AddField(
            model_name='accfifa',
            name='product',
            field=models.BooleanField(default=True),
        ),
    ]
