# Generated by Django 4.0.5 on 2022-06-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_accfifa_status_accfifa_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accfifa',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
