# Generated by Django 4.0.5 on 2022-06-23 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_accfifa_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='accfifa',
            name='timeUpload',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
