# Generated by Django 4.0.5 on 2022-06-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_accfifa_timeupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='accfifa',
            name='sale',
            field=models.DecimalField(decimal_places=3, default=50.0, max_digits=10),
        ),
    ]
