# Generated by Django 4.0.5 on 2022-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
