# Generated by Django 4.0.5 on 2022-06-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='accfifa',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
