# Generated by Django 4.0.5 on 2022-06-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_accfifa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='accfifa',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='accfifa',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
