# Generated by Django 4.0.5 on 2022-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_accfifa_image1_accfifa_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='accfifa',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
