# Generated by Django 4.0.5 on 2022-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_accfifa_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='accfifa',
            name='password',
            field=models.CharField(default='xyz', max_length=255),
        ),
        migrations.AddField(
            model_name='accfifa',
            name='username',
            field=models.CharField(default='abc', max_length=255),
        ),
    ]
