# Generated by Django 4.0.5 on 2022-07-12 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_acccategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='accfifa',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.acccategory'),
        ),
    ]
