# Generated by Django 4.0.5 on 2022-07-29 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_shopcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcart',
            name='number',
        ),
        migrations.RemoveField(
            model_name='shopcart',
            name='slug',
        ),
    ]
