# Generated by Django 4.0.5 on 2022-07-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_cart_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='addCart',
            field=models.BooleanField(default=False),
        ),
    ]
